# app/config/routing.yml

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /

# On inclut également les routes de notre CoreBundle, sans préfixe
oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"


