# src/OC/PlatformBundle/Resources/config/services.yml

services:
  oc_platform.antispam:
      class: OC\PlatformBundle\Antispam\OCAntispam
      arguments:
          - "@mailer"
          - %locale%
          - 50

  oc_platform.email.application_mailer:
      class: OC\PlatformBundle\Email\ApplicationMailer
      arguments:
          - "@mailer"

  
  oc_platform.purger.advert:
    class: OC\PlatformBundle\Purger\AdvertPurger
    arguments:
      - "@doctrine.orm.entity_manager"
